import { MD3LightTheme, type MD3Theme } from 'react-native-paper';

// esta paleta replica los colores del sistema visual del zip.
export const brandPalette = {
  background: '#FBF9F8',
  error: '#BA1A1A',
  errorContainer: '#FFDAD6',
  inverseOnSurface: '#F2F0F0',
  inversePrimary: '#88D982',
  inverseSurface: '#303030',
  onBackground: '#1B1C1C',
  onError: '#FFFFFF',
  onErrorContainer: '#93000A',
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#CBFFC2',
  onSecondary: '#FFFFFF',
  onSecondaryContainer: '#656464',
  onSurface: '#1B1C1C',
  onSurfaceVariant: '#40493D',
  onTertiary: '#FFFFFF',
  onTertiaryContainer: '#F1F1F1',
  outline: '#707A6C',
  outlineVariant: '#BFCABA',
  primary: '#0D631B',
  primaryContainer: '#2E7D32',
  primaryStrong: '#0D631B',
  secondary: '#5F5E5E',
  secondaryContainer: '#E5E2E1',
  surface: '#FBF9F8',
  surfaceContainer: '#F0EDED',
  surfaceContainerHigh: '#EAE8E7',
  surfaceContainerLow: '#F5F3F3',
  surfaceContainerLowest: '#FFFFFF',
  surfaceVariant: '#E4E2E1',
  tertiary: '#545656',
  tertiaryContainer: '#6C6E6E',
};

// este theme queda listo para paper y reutiliza la paleta del sistema visual.
export const paperTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 8,
  colors: {
    ...MD3LightTheme.colors,
    background: brandPalette.background,
    error: brandPalette.error,
    errorContainer: brandPalette.errorContainer,
    inverseOnSurface: brandPalette.inverseOnSurface,
    inversePrimary: brandPalette.inversePrimary,
    inverseSurface: brandPalette.inverseSurface,
    onBackground: brandPalette.onBackground,
    onError: brandPalette.onError,
    onErrorContainer: brandPalette.onErrorContainer,
    onPrimary: brandPalette.onPrimary,
    onPrimaryContainer: brandPalette.onPrimaryContainer,
    onSecondary: brandPalette.onSecondary,
    onSecondaryContainer: brandPalette.onSecondaryContainer,
    onSurface: brandPalette.onSurface,
    onSurfaceVariant: brandPalette.onSurfaceVariant,
    onTertiary: brandPalette.onTertiary,
    onTertiaryContainer: brandPalette.onTertiaryContainer,
    outline: brandPalette.outline,
    outlineVariant: brandPalette.outlineVariant,
    primary: brandPalette.primaryContainer,
    primaryContainer: brandPalette.primaryContainer,
    secondary: brandPalette.secondary,
    secondaryContainer: brandPalette.secondaryContainer,
    surface: brandPalette.surfaceContainerLowest,
    surfaceDisabled: brandPalette.surfaceVariant,
    surfaceVariant: brandPalette.surfaceVariant,
    tertiary: brandPalette.tertiary,
    tertiaryContainer: brandPalette.tertiaryContainer,
  },
};
