/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/change-password`; params?: Router.UnknownInputParams; } | { pathname: `/create-post`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/messages-by-post`; params?: Router.UnknownInputParams; } | { pathname: `/my-posts`; params?: Router.UnknownInputParams; } | { pathname: `/personal-data`; params?: Router.UnknownInputParams; } | { pathname: `/safety`; params?: Router.UnknownInputParams; } | { pathname: `/saved-posts`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/conversation/[threadId]`, params: Router.UnknownInputParams & { threadId: string | number; } } | { pathname: `/edit-post/[postId]`, params: Router.UnknownInputParams & { postId: string | number; } } | { pathname: `/post/[postId]`, params: Router.UnknownInputParams & { postId: string | number; } } | { pathname: `/profile/[authorId]`, params: Router.UnknownInputParams & { authorId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/change-password`; params?: Router.UnknownOutputParams; } | { pathname: `/create-post`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/messages-by-post`; params?: Router.UnknownOutputParams; } | { pathname: `/my-posts`; params?: Router.UnknownOutputParams; } | { pathname: `/personal-data`; params?: Router.UnknownOutputParams; } | { pathname: `/safety`; params?: Router.UnknownOutputParams; } | { pathname: `/saved-posts`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/conversation/[threadId]`, params: Router.UnknownOutputParams & { threadId: string; } } | { pathname: `/edit-post/[postId]`, params: Router.UnknownOutputParams & { postId: string; } } | { pathname: `/post/[postId]`, params: Router.UnknownOutputParams & { postId: string; } } | { pathname: `/profile/[authorId]`, params: Router.UnknownOutputParams & { authorId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/change-password${`?${string}` | `#${string}` | ''}` | `/create-post${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/messages-by-post${`?${string}` | `#${string}` | ''}` | `/my-posts${`?${string}` | `#${string}` | ''}` | `/personal-data${`?${string}` | `#${string}` | ''}` | `/safety${`?${string}` | `#${string}` | ''}` | `/saved-posts${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/change-password`; params?: Router.UnknownInputParams; } | { pathname: `/create-post`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/messages-by-post`; params?: Router.UnknownInputParams; } | { pathname: `/my-posts`; params?: Router.UnknownInputParams; } | { pathname: `/personal-data`; params?: Router.UnknownInputParams; } | { pathname: `/safety`; params?: Router.UnknownInputParams; } | { pathname: `/saved-posts`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/conversation/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/edit-post/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/post/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/profile/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/conversation/[threadId]`, params: Router.UnknownInputParams & { threadId: string | number; } } | { pathname: `/edit-post/[postId]`, params: Router.UnknownInputParams & { postId: string | number; } } | { pathname: `/post/[postId]`, params: Router.UnknownInputParams & { postId: string | number; } } | { pathname: `/profile/[authorId]`, params: Router.UnknownInputParams & { authorId: string | number; } };
    }
  }
}
